### ISSUE TITLE
Prettier config setup for single quotes

### ISSUE THREAD

**Issue by ineptian** [TrellisCommerce/shopify-tailwind-starter-base#15]
## Describe the current behavior
Files inside the snippets folder, ignore the prettierrc.json settings for some reason. This causes them to fall back to the settings in the npm package. The settings in the npm package have singleQuotes set to true, so every single time you save or format a page in the snippets directory, all the double quotes get changed to single quotes. If you delete the prettier setting in package,json, it works as expected.

## Describe the expected behavior
Double quotes should stay double quotes

## Version information (Dawn, browsers and operating systems)

Latest version of this theme on dawn 12.

**Comment by cmegalo** [comment]
@ineptian this is due to the `@trelliscommerce/prettier-config` dependency. You can `npm uninstall @trelliscommerce/prettier-config` and remove `"prettier": "@trelliscommerce/prettier-config"` from `package.json` if you do not want to use this dependency.
