### ISSUE TITLE
Error when filtering

### ISSUE THREAD

**Issue by gjportegies** [TrellisCommerce/shopify-tailwind-starter-base#21]
## Describe the current behavior

When filtering on a collection page I'm getting the following error on the browser console and the page gets stuck:
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'innerHTML')
    at FacetFiltersForm.renderProductGridContainer (facets.js:97:45)
    at facets.js:78:26
```

## Describe the expected behavior
The collection should be filtered.

## Version information (Dawn, browsers and operating systems)

- Dawn Version: 13.0.1
- Latest version of this starter base

## Additional context/screenshots
To confirm I've also downloaded this package as zip and installed directly as theme.

**Comment by cmegalo** [comment]
@gjportegies I believe this is fixed now that the code is updated to reflect Dawn v14.0.0
