### ISSUE TITLE
 not working

### ISSUE THREAD

**Issue by kikohz** [TrellisCommerce/shopify-tailwind-starter-base#23]
## Describe the current behavior
I cloned the repository and linked to my shopify, I ran shopify theme dev --store=mystore.myshopify.com locally and synced to shopify, I changed my code and saw the changes in the preview url, but when I use tailwind. It doesn't work
my code ：`<div class='twcss-bg-red-400'>Hello World</div>`

## Describe the expected behavior
I set the div background color, but it doesn't work

## Version information (Dawn, browsers and operating systems)

- Dawn Version: 14.0.0
- Chrome Version 108.0.5359.124
- macOS Version 13.1

## Additional context/screenshots

<img width="376" alt="Screenshot 2024-05-24 at 10 20 31 AM" src="https://github.com/TrellisCommerce/shopify-tailwind-starter-base/assets/1294534/d95f22f9-518e-4806-99f6-8bfb00411e8e">
<img width="459" alt="Screenshot 2024-05-24 at 10 21 25 AM" src="https://github.com/TrellisCommerce/shopify-tailwind-starter-base/assets/1294534/094ef9f8-dc0d-4937-a8b8-116bfd0a8bf8">

**Comment by BobUzh** [comment]
@kikohz I tried and it worked for me
![image](https://github.com/TrellisCommerce/shopify-tailwind-starter-base/assets/58395920/c73a08e5-d47e-42f9-a2c9-d18060110f2e)
See if you have styles for this class, maybe you forgot to build the css

**Comment by BobUzh** [comment]
@kikohz  I tried and it worked for me
![image](https://github.com/TrellisCommerce/shopify-tailwind-starter-base/assets/58395920/7cff9a8f-2fe8-426d-ad2e-6b57bd70fe0c)
See if you have styles for this class, maybe you forgot to build the css

**Comment by cmegalo** [comment]
@kikohz thank you for the big report! Like @BobUzh pointed out, make sure that your TailwindCSS file has been compiled locally, which can be accomplished by running `npx tailwindcss -i ./assets/app-tailwind.css -o ./assets/app.css --watch` in a separate terminal in the theme directory
