### ISSUE TITLE
Different compiled app.css

### ISSUE THREAD

**Issue by danharper83** [TrellisCommerce/shopify-tailwind-starter-base#32]
I seem to be getting different app.css files when github action compiles the app.css to what my local compiles.

Usually minor things like formatting the same css rules but slightly different.

This is causing me issues when pushing because I immediately have to pull down the code again after the action has compiled it. 

This is causing other strange issue which I have never seen in git before where when I try and pull down the changed code from github it says I have changes in the app.css that have not been committed but my working branch is clean. When I check `git status` there is nothing.

I noticed the action is compiling with tailwind 3.4.11 so I forced my local version to that but that still hasn't solved the issue.

**Comment by cmegalo** [comment]
@danharper83 I think I ran into a similar issue at one point, and it seemed to resolve itself when I removed the app.css file locally for the next commit I wanted to make. Once the commit was made, the issue has not popped up again, but let me know if this does not resolve it for you.

**Comment by danharper83** [comment]
That didn't solve it.

There seems to be some difference between how the github action compiles tailwind and the front end stack. It may be machine specific, something to do with line endings or spacing.
