### ISSUE TITLE
Is everything that should be included in .shopifyignore in there?

### ISSUE THREAD

**Issue by ineptian** [TrellisCommerce/shopify-tailwind-starter-base#5]
Are `package.json` and  `package-lock.json` the only things that need to be in there? Should `node_modules` and anything else related to  dev stuff also be included?

**Comment by cmegalo** [comment]
Hi @ineptian. The main reason I added those 2 files to `.shopifyignore` was due to warnings that would pop up when running the Shopify CLI. I did not get warnings regarding any other files.
