### ISSUE TITLE
No longer maintained?!

### ISSUE THREAD

**Issue by TimoSolo** [TrellisCommerce/shopify-tailwind-starter-base#6]
After investing many hours getting this theme running, I realised it is 2 major versions behind the current Dawn theme. https://github.com/Shopify/dawn

If it is no longer maintained, please put a warning in the README so that it can be used for reference but not production! Or update it to the latest version of Dawn? 🙏

**Comment by cmegalo** [comment]
Hi @TimoSolo, sorry for the lag in updating the theme. I am currently working on getting it up to date with Dawn's latest. I will close when complete.

**Comment by cmegalo** [comment]
The tailwind starter theme has now been updated with the latest from Dawn v8.0.0.

**Comment by TimoSolo** [comment]
Thanks so much! very happy that it is still being kept up to date - appreciate your hard work!

**Comment by rcesonis** [comment]
when using prefix twcss-* , hover effect is not working, is there any plans to fix it?

**Comment by cmegalo** [comment]
@rcesonis this seems to be working just fine! Make sure the syntax of your class is something like `hover:twcss-bg-black` when dealing with the `twcss-` prefix.
